### ISSUE TITLE
Hello, I can not correspond the phrase with its coarse category.

### ISSUE THREAD

**Issue by junleiz** [BryanPlummer/cite#2]
Hello:
    I am a master student and am trying to do some jobs about this excellent job.  I failed to use your plc-c code to compute the HGLMM features. I spent several days fixing it but it still said some of the words do not exist in the vocabulary. So I decided to use your uploaded text features to do the experiments. But in the ***_imfeats.h5 files, there are no features like phrase_id or  phrase_type. I really do not know how to correspond the phrases their coarse category like "people, scene". Could you please tell me how do you do it?

Thank you very much for your precious time！

**Comment by BryanPlummer** [comment]
Not all words will exist in a vocabulary, this is expected behavior.  An alternative is to use word2vec or fasttext features instead, which should work roughly as well.  As far as how to match phrases to the course category, these comes from the original Flickr30K Entities annotations, and can be obtained from there.
